# Monitoring resources kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: imagen

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: imagen
    includeSelectors: false

resources:
  - pod-monitoring.yaml
  - rules.yaml
