# Autoscaling kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - custom-metrics-adapter.yaml
  - upscale-hpa.yaml
  - enhance-hpa.yaml
  - comic-hpa.yaml
  - style-aged-hpa.yaml
  - background-remove-hpa.yaml
