# Workers kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upscale-worker.yaml
  - enhance-worker.yaml
  - comic-worker.yaml
  - style-aged-worker.yaml
  - background-remove-worker.yaml
